# Generated by Django 2.2.5 on 2019-12-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task1Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_latent_semantics', models.CharField(max_length=3, verbose_name='Number of Latent Semantics')),
                ('labelled_folder_name', models.CharField(max_length=100, verbose_name='Labelled Folder Path')),
                ('unlabelled_folder_name', models.CharField(max_length=100, verbose_name='Unlabelled Folder Path')),
            ],
        ),
        migrations.CreateModel(
            name='Task2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_clusters', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Task3Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_similar_images', models.CharField(max_length=2, verbose_name='Number of Most Similar Images')),
                ('k', models.CharField(max_length=3, verbose_name='Number of outgoing Edges(k)')),
                ('K', models.CharField(max_length=3, verbose_name='Number of most Dominant Images(K)')),
                ('folder_name', models.CharField(max_length=100, verbose_name='Folder Path')),
                ('user_images', models.CharField(max_length=200, verbose_name='User Preferred Images(Personalized)')),
            ],
        ),
        migrations.CreateModel(
            name='Task4Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier', models.CharField(choices=[('Support Vector Machine', 'Support Vector Machine'), ('Decision Tree Classifier', 'Decision Tree Classifier'), ('Personalized Page Rank', 'Personalized Page Rank')], default='Support Vector Machine', max_length=6)),
                ('dataset', models.CharField(choices=[('set1', 'set1'), ('set2', 'set2'), ('set3', 'set3'), ('set4', 'set4')], default='set1', max_length=6)),
                ('labelled_folder_name', models.CharField(max_length=100, verbose_name='Labelled Folder Path')),
                ('unlabelled_folder_name', models.CharField(max_length=100, verbose_name='Unlabelled Folder Path')),
            ],
        ),
        migrations.CreateModel(
            name='Task5Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_layers', models.CharField(max_length=2)),
                ('number_of_hashes_per_layer', models.CharField(max_length=2)),
                ('set_of_vectors', models.CharField(max_length=2)),
                ('query_image', models.CharField(max_length=100)),
                ('most_similar_images', models.CharField(max_length=2, verbose_name='Number of Most Similar Images')),
                ('relevance_feedback', models.CharField(choices=[('Support Vector Machine', 'Support Vector Machine'), ('Decision Tree Classifier', 'Decision Tree Classifier'), ('Personalized Page Rank', 'Personalized Page Rank'), ('Probabilistic', 'Probabilistic'), ('None', 'None')], default='None', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Task6Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_feedback', models.CharField(choices=[('Support Vector Machine', 'Support Vector Machine'), ('Decision Tree Classifier', 'Decision Tree Classifier'), ('Personalized Page Rank', 'Personalized Page Rank'), ('Probabilistic', 'Probabilistic'), ('None', 'None')], default='Probabilistic', max_length=6)),
            ],
        ),
    ]
