# Generated by Django 2.2.5 on 2019-12-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task4model',
            name='kernel',
            field=models.CharField(choices=[('linear', 'linear'), ('poly', 'poly'), ('rbf', 'rbf')], default='linear', max_length=6),
        ),
    ]
